# =====================================================
# Sidebar Layout Configuration
#
# - The order of sections below determines their display order in the sidebar.
# - To remove a page from the sidebar, simply delete the corresponding item.
# =====================================================

sidebar:
  userName: "Siwei Chen" # Name displayed at the top of the sidebar
  profileImage: https://github.com/Reggiws/reggiws.github.io/tree/4f599ae0cde7d3c93458aaf96b8f2ca15e2f855d/public/images/wechat_2026-06-24_154810_385.png # Profile image URL
  sections:
    - title: About Me
      url: ""
      icon:
        name: LuUser
        package: "react-icons/lu"

    - title: Projects
      url: "projects"
      icon:
        name: LuWrench
        package: "react-icons/lu"

    # - title: Publications
    #   url: "publications"
    #   icon:
    #     name: LuLibraryBig
    #     package: "react-icons/lu"

    # - title: Articles
    #   url: "articles"
    #   icon:
    #     name: LuNewspaper
    #     package: "react-icons/lu"

    - title: Movies
      url: "movies"
      icon:
        name: LuClapperboard
        package: "react-icons/lu"

    # - title: Music
    #   url: "music"
    #   icon:
    #     name: LuMusic
    #     package: "react-icons/lu"
