# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Profile"
  repoUrl: "https://github.com/Reggiws/reggiws.github.io"
  description: "A short description"
  author: "Siwei Chen"
